### ISSUE TITLE
objectsGS: RPoint has no attributes _name, _smooth

### ISSUE THREAD

**Issue by jenskutilek** [schriftgestalt/Glyphs-Scripts#13]
https://github.com/schriftgestalt/Glyphs-Scripts/blob/master/objectsGS.py#L1227

Asking an RPoint for its name or smoothness will raise an AttributeError, because RPoint.name and RPoint.smooth are not initialized and not available from the gs_point.

**Comment by schriftgestalt** [comment]
fixed it (#8a6f8f40ef)
