### ISSUE TITLE
[Glyphs Import.py] Shifted Components

### ISSUE THREAD

**Issue by arialcrime** [schriftgestalt/Glyphs-Scripts#21]
Anchor information seems to be ignored when importing single master files. 
After duplicating the master and generating an instance of it, the script works fine.

![bildschirmfoto 2016-02-29 um 11 52 18](https://cloud.githubusercontent.com/assets/2954154/13674990/e98782b8-e6df-11e5-8a37-3b596ea92c92.png)

**Comment by schriftgestalt** [comment]
The anchors do not matter in FLS. And I can’t reproduce it.

**Comment by arialcrime** [comment]
I sent you some more comprehensive files yesterday.

**Comment by schriftgestalt** [comment]
Yes. And the file works fine for me.

**Comment by arialcrime** [comment]
Okay, I will investigate further.
