### ISSUE TITLE
Glyphs Export.py: SyntaxError: 'utf8' codec can't decode byte 0x9f in position 4859: invalid start byte

### ISSUE THREAD

**Issue by m4rc1e** [schriftgestalt/Glyphs-Scripts#31]
Hey Georg,

Just a heads up, 

```
#FLM: Glyphs Export
# -*- coding: utf8 -*-
# Version 0.6 (1. April 2014)
```

produces the following traceback:

```
  File "<string>", line 0
SyntaxError: 'utf8' codec can't decode byte 0x9f in position 4859: invalid start byte
```

When I remove the `# -*- coding: utf8 -*-` it works just fine.

I am running FL 5.1.5 mac, build 5714. OS X 10.11.3. This FL is running Python:
2.7.10 (default, Oct 23 2015, 18:05:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

Cheers,
Marc

**Comment by schriftgestalt** [comment]
could you send me the .vfb file?

**Comment by m4rc1e** [comment]
mail sent.
