### ISSUE TITLE
Importing objectsGS fails

### ISSUE THREAD

**Issue by madig** [schriftgestalt/Glyphs-Scripts#36]
Execute the following in the macro window: `import objectsGS`
```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/nikolaus/Library/Application Support/Glyphs/Scripts/objectsGS.py", line 42, in <module>
    if type(GSElement.parent) != type(GSGlyph.parent):
NameError: name 'GSElement' is not defined
```
This breaks e.g. HT Letterspacer.

**Comment by schriftgestalt** [comment]
did you get the latest version of the file?

**Comment by madig** [comment]
I got whatever the "get modules" button got.

**Comment by schriftgestalt** [comment]
can you send me the version you have?

**Comment by madig** [comment]
https://raw.githubusercontent.com/schriftgestalt/Glyphs-Scripts/bda5f23d888c6c9bf532612d9db42c81e89c8860/objectsGS.py

**Comment by madig** [comment]
Okay. Where does the updater get the file from?
