### ISSUE TITLE
Fontlab Import mark colors

### ISSUE THREAD

**Issue by weiweihuanghuang** [schriftgestalt/Glyphs-Scripts#8]
Exporting .glyphs keeps the colour marks but not importing?

**Comment by weiweihuanghuang** [comment]
Actually it does import, just not all the colors, works good enough for me

**Comment by weiweihuanghuang** [comment]
Actually I closed this too quick, it's not really importing the marks properly. Only some even for the color that works.

**Comment by schriftgestalt** [comment]
Implemented import of mark colors. 
The two gray colors are not supported by FLS and are ignored.
Some glyphs might have been marked red in the previous version. That where all not exporting glyphs.
